import React, { useState } from 'react';
import api from '../api/axiosConfig';
import {
  TrendingUp, TrendingDown, IndianRupee, Download,
  Printer, RefreshCw, Scale, CheckCircle, AlertCircle
} from 'lucide-react';

const fmt = (n) =>
  `₹${(Number(n) || 0).toLocaleString('en-IN', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;

const BalanceSheet = () => {
  const [data,    setData]    = useState(null);
  const [loading, setLoading] = useState(false);
  const [msg,     setMsg]     = useState({ text: '', type: '' });

  const fetchBalanceSheet = async () => {
    setLoading(true);
    setData(null);
    try {
      const res = await api.get('/finance/balance-sheet');
      setData(res.data);
    } catch {
      showMsg('Failed to fetch balance sheet. Check backend.', 'error');
    } finally {
      setLoading(false);
    }
  };

  const showMsg = (text, type) => {
    setMsg({ text, type });
    setTimeout(() => setMsg({ text: '', type: '' }), 4000);
  };

  // ── CSV Export ─────────────────────────────────────────────────────────
  const exportCSV = () => {
    if (!data) return;
    const rows = [
      [`BALANCE SHEET — As of ${data.asOfDate}`],
      [],
      ['ASSETS'],
      ['Inventory Value (Stock at Cost)', data.inventoryValue],
      ['Customer Receivables (Udhaar)', data.customerReceivables],
      ['Total Revenue Collected (Cash)', data.totalRevenueCollected],
      ['TOTAL ASSETS', data.totalAssets],
      [],
      ['LIABILITIES'],
      ['Total Purchases (Stock Cost)', data.totalPurchases],
      ['Total Operational Expenses', data.totalExpenses],
      ['Net GST Payable', data.netGstPayable],
      ['TOTAL LIABILITIES', data.totalLiabilities],
      [],
      ['NET WORTH (Assets - Liabilities)', data.netWorth],
    ];
    const csv  = rows.map(r => r.join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = `BalanceSheet_${data.asOfDate}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // ── Print ──────────────────────────────────────────────────────────────
  const printReport = () => {
    if (!data) return;
    const html = `<html><head><style>
      body{font-family:Arial,sans-serif;padding:30px;color:#111}
      h1{color:#2563eb;border-bottom:2px solid #2563eb;padding-bottom:8px}
      h2{color:#1e40af;font-size:15px;margin:20px 0 8px}
      table{width:100%;border-collapse:collapse;margin-bottom:16px}
      th{background:#2563eb;color:white;padding:9px 12px;text-align:left;font-size:13px}
      td{padding:9px 12px;border-bottom:1px solid #e2e8f0;font-size:13px}
      .total td{font-weight:bold;font-size:15px;border-top:2px solid #2563eb;background:#eff6ff}
      .green{color:#16a34a;font-weight:bold}
      .red{color:#dc2626;font-weight:bold}
      .net{font-size:18px;font-weight:bold}
    </style></head><body>
      <h1>Balance Sheet — As of ${data.asOfDate}</h1>

      <h2>Assets</h2>
      <table>
        <tr><th>Particulars</th><th>Amount</th></tr>
        <tr><td>Inventory Value (Stock at Cost Price)</td><td class="green">${fmt(data.inventoryValue)}</td></tr>
        <tr><td>Customer Receivables (Udhaar Outstanding)</td><td class="green">${fmt(data.customerReceivables)}</td></tr>
        <tr><td>Total Revenue Collected (Cash Sales)</td><td class="green">${fmt(data.totalRevenueCollected)}</td></tr>
        <tr class="total"><td>TOTAL ASSETS</td><td class="green">${fmt(data.totalAssets)}</td></tr>
      </table>

      <h2>Liabilities</h2>
      <table>
        <tr><th>Particulars</th><th>Amount</th></tr>
        <tr><td>Total Purchases (Stock Procurement Cost)</td><td class="red">${fmt(data.totalPurchases)}</td></tr>
        <tr><td>Total Operational Expenses</td><td class="red">${fmt(data.totalExpenses)}</td></tr>
        <tr><td>Net GST Payable to Government</td><td class="red">${fmt(data.netGstPayable)}</td></tr>
        <tr class="total"><td>TOTAL LIABILITIES</td><td class="red">${fmt(data.totalLiabilities)}</td></tr>
      </table>

      <table>
        <tr class="total">
          <td class="net">NET WORTH (Assets − Liabilities)</td>
          <td class="net ${data.netWorth >= 0 ? 'green' : 'red'}">${fmt(data.netWorth)}</td>
        </tr>
      </table>

      <p style="color:#94a3b8;font-size:11px;margin-top:30px">
        Generated by RxManager Pro — ${new Date().toLocaleString('en-IN')}
      </p>
    </body></html>`;
    const w = window.open('', '_blank');
    w.document.write(html);
    w.document.close();
    w.focus();
    setTimeout(() => w.print(), 600);
  };

  return (
    <div style={s.page}>

      {/* Header */}
      <div style={s.header}>
        <div>
          <h1 style={s.h1}>Balance Sheet</h1>
          <p style={s.subtitle}>Assets · Liabilities · Net Worth — snapshot of financial position</p>
        </div>
        <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}>
          {data && (
            <>
              <button onClick={exportCSV} style={s.csvBtn}>
                <Download size={15}/> Export CSV
              </button>
              <button onClick={printReport} style={s.printBtn}>
                <Printer size={15}/> Print / PDF
              </button>
            </>
          )}
        </div>
      </div>

      {/* Toast */}
      {msg.text && (
        <div style={{ ...s.toast, ...(msg.type === 'success' ? s.toastOk : s.toastErr) }}>
          {msg.type === 'success' ? <CheckCircle size={16}/> : <AlertCircle size={16}/>}
          {msg.text}
        </div>
      )}

      {/* Generate button */}
      <div style={{ marginBottom: '28px' }}>
        <button onClick={fetchBalanceSheet} disabled={loading} style={s.fetchBtn}>
          {loading
            ? <><RefreshCw size={15} style={{ animation: 'spin 1s linear infinite' }}/> Loading...</>
            : <><Scale size={15}/> Generate Balance Sheet</>}
        </button>
        {data && (
          <span style={{ color: '#64748b', fontSize: '13px', marginLeft: '16px' }}>
            As of {new Date(data.asOfDate).toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}
          </span>
        )}
      </div>

      {/* Empty state */}
      {!data && !loading && (
        <div style={s.emptyBox}>
          <Scale size={48} color="#334155"/>
          <p style={{ color: '#94a3b8', marginTop: '16px', fontSize: '15px' }}>
            Click <strong style={{ color: 'white' }}>Generate Balance Sheet</strong> to view your financial position
          </p>
        </div>
      )}

      {data && (
        <>
          {/* Net worth banner */}
          <div style={{
            ...s.netBanner,
            borderColor:       data.netWorth >= 0 ? '#10b981' : '#ef4444',
            backgroundColor:   data.netWorth >= 0 ? 'rgba(16,185,129,0.08)' : 'rgba(239,68,68,0.08)',
          }}>
            <IndianRupee size={28} color={data.netWorth >= 0 ? '#10b981' : '#ef4444'}/>
            <div>
              <div style={{ color: '#94a3b8', fontSize: '12px', fontWeight: '800', letterSpacing: '0.05em' }}>
                NET WORTH (ASSETS − LIABILITIES)
              </div>
              <div style={{
                color:      data.netWorth >= 0 ? '#10b981' : '#ef4444',
                fontSize:   '36px',
                fontWeight: '700',
                lineHeight: '1.1'
              }}>
                {fmt(data.netWorth)}
              </div>
              <div style={{ color: '#64748b', fontSize: '12px', marginTop: '4px' }}>
                {data.netWorth >= 0
                  ? '✓ Business is in positive financial health'
                  : '⚠ Liabilities exceed assets — review expenses'}
              </div>
            </div>
          </div>

          {/* Two column layout */}
          <div style={s.twoCol}>

            {/* ASSETS */}
            <div style={s.tableCard}>
              <h3 style={{ ...s.tableTitle, color: '#10b981' }}>
                <TrendingUp size={18} color="#10b981"/> Assets
              </h3>
              <table style={s.table}>
                <thead>
                  <tr>
                    <th style={s.th}>Particulars</th>
                    <th style={{ ...s.th, textAlign: 'right' }}>Amount</th>
                  </tr>
                </thead>
                <tbody>
                  {[
                    {
                      label: 'Inventory Value',
                      sub:   'Current stock at cost price',
                      val:   data.inventoryValue,
                    },
                    {
                      label: 'Customer Receivables',
                      sub:   'Udhaar / outstanding credit',
                      val:   data.customerReceivables,
                    },
                    {
                      label: 'Cash Collected',
                      sub:   'Total non-credit sales revenue',
                      val:   data.totalRevenueCollected,
                    },
                  ].map((row, i) => (
                    <tr key={i} style={s.tr}>
                      <td style={s.td}>
                        <div style={{ color: 'white', fontWeight: '500' }}>{row.label}</div>
                        <div style={{ color: '#64748b', fontSize: '11px' }}>{row.sub}</div>
                      </td>
                      <td style={{ ...s.td, textAlign: 'right', color: '#10b981', fontWeight: '600' }}>
                        {fmt(row.val)}
                      </td>
                    </tr>
                  ))}
                  {/* Total row */}
                  <tr style={{ borderTop: '2px solid #10b981', backgroundColor: 'rgba(16,185,129,0.06)' }}>
                    <td style={{ ...s.td, fontWeight: '700', color: 'white', fontSize: '15px' }}>
                      TOTAL ASSETS
                    </td>
                    <td style={{ ...s.td, textAlign: 'right', color: '#10b981', fontWeight: '700', fontSize: '18px' }}>
                      {fmt(data.totalAssets)}
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>

            {/* LIABILITIES */}
            <div style={s.tableCard}>
              <h3 style={{ ...s.tableTitle, color: '#ef4444' }}>
                <TrendingDown size={18} color="#ef4444"/> Liabilities
              </h3>
              <table style={s.table}>
                <thead>
                  <tr>
                    <th style={s.th}>Particulars</th>
                    <th style={{ ...s.th, textAlign: 'right' }}>Amount</th>
                  </tr>
                </thead>
                <tbody>
                  {[
                    {
                      label: 'Total Purchases',
                      sub:   'Stock procurement cost (all time)',
                      val:   data.totalPurchases,
                    },
                    {
                      label: 'Operational Expenses',
                      sub:   'Rent, food, transport, utilities',
                      val:   data.totalExpenses,
                    },
                    {
                      label: 'Net GST Payable',
                      sub:   'Output tax − input tax credit',
                      val:   data.netGstPayable,
                    },
                  ].map((row, i) => (
                    <tr key={i} style={s.tr}>
                      <td style={s.td}>
                        <div style={{ color: 'white', fontWeight: '500' }}>{row.label}</div>
                        <div style={{ color: '#64748b', fontSize: '11px' }}>{row.sub}</div>
                      </td>
                      <td style={{ ...s.td, textAlign: 'right', color: '#f87171', fontWeight: '600' }}>
                        {fmt(row.val)}
                      </td>
                    </tr>
                  ))}
                  {/* Total row */}
                  <tr style={{ borderTop: '2px solid #ef4444', backgroundColor: 'rgba(239,68,68,0.06)' }}>
                    <td style={{ ...s.td, fontWeight: '700', color: 'white', fontSize: '15px' }}>
                      TOTAL LIABILITIES
                    </td>
                    <td style={{ ...s.td, textAlign: 'right', color: '#ef4444', fontWeight: '700', fontSize: '18px' }}>
                      {fmt(data.totalLiabilities)}
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          {/* Accounting equation note */}
          <div style={{
            backgroundColor: '#1e293b', border: '1px solid #334155',
            borderRadius: '12px', padding: '16px 20px',
            display: 'flex', alignItems: 'center', gap: '12px',
            fontSize: '13px', color: '#94a3b8', marginTop: '4px'
          }}>
            <Scale size={16} color="#60a5fa"/>
            <span>
              <strong style={{ color: 'white' }}>Accounting equation:</strong>{' '}
              Assets ({fmt(data.totalAssets)}) − Liabilities ({fmt(data.totalLiabilities)}) ={' '}
              <strong style={{ color: data.netWorth >= 0 ? '#10b981' : '#ef4444' }}>
                Net Worth {fmt(data.netWorth)}
              </strong>
            </span>
          </div>
        </>
      )}

      <style>{`@keyframes spin{from{transform:rotate(0deg)}to{transform:rotate(360deg)}}`}</style>
    </div>
  );
};

// ── Styles ─────────────────────────────────────────────────────────────────────
const s = {
    page:      { padding: '40px', marginLeft: '240px', backgroundColor: '#0f172a', minHeight: '100vh' },
    header:    { display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px', flexWrap: 'wrap', gap: '12px' },
    h1:        { color: '#f1f5f9', margin: '0 0 4px', fontSize: '26px', fontWeight: '600' },
    subtitle:  { color: '#94a3b8', margin: 0, fontSize: '14px' },
    toast:     { display: 'flex', alignItems: 'center', gap: '10px', padding: '14px 18px', borderRadius: '8px', marginBottom: '20px', fontSize: '14px' },
    toastOk:   { backgroundColor: 'rgba(16,185,129,0.1)', color: '#10b981', border: '1px solid #10b981' },
    toastErr:  { backgroundColor: 'rgba(239,68,68,0.1)', color: '#ef4444', border: '1px solid #ef4444' },
    fetchBtn:  { display: 'inline-flex', alignItems: 'center', gap: '8px', backgroundColor: '#2563eb', color: 'white', border: 'none', padding: '11px 24px', borderRadius: '8px', fontWeight: 'bold', cursor: 'pointer', fontSize: '14px' },
    csvBtn:    { display: 'flex', alignItems: 'center', gap: '8px', backgroundColor: '#10b981', color: 'white', border: 'none', padding: '10px 18px', borderRadius: '8px', fontWeight: 'bold', cursor: 'pointer', fontSize: '13px' },
    printBtn:  { display: 'flex', alignItems: 'center', gap: '8px', backgroundColor: '#7c3aed', color: 'white', border: 'none', padding: '10px 18px', borderRadius: '8px', fontWeight: 'bold', cursor: 'pointer', fontSize: '13px' },
    emptyBox:  { textAlign: 'center', padding: '80px 0' },
    netBanner: { display: 'flex', alignItems: 'center', gap: '20px', backgroundColor: '#1e293b', border: '2px solid', borderRadius: '16px', padding: '24px 28px', marginBottom: '24px' },
    twoCol:    { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px', marginBottom: '20px' },
    tableCard: { backgroundColor: '#1e293b', borderRadius: '16px', border: '1px solid #334155', padding: '24px' },
    tableTitle:{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '16px', fontWeight: '600', margin: '0 0 16px' },
    table:     { width: '100%', borderCollapse: 'collapse' },
    th:        { textAlign: 'left', padding: '10px 12px', backgroundColor: '#0f172a', color: '#94a3b8', fontSize: '11px', textTransform: 'uppercase', letterSpacing: '0.04em', borderBottom: '1px solid #334155' },
    td:        { padding: '13px 12px', color: '#cbd5e1', borderBottom: '1px solid #1e293b', fontSize: '14px' },
    tr:        { transition: 'background 0.1s' },
};

export default BalanceSheet;